//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDiary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Diary
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public int Importance { get; set; }
        [Required,DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        [Required]
        public string Note { get; set; }
        public string Image { get; set; }
        public System.DateTime LastModification { get; set; }
        public int UserId { get; set; }
    
        public virtual Importance Importance1 { get; set; }
        public virtual User User { get; set; }
    }
}
