//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDiary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Importance
    {
        public Importance()
        {
            this.Diaries = new HashSet<Diary>();
        }
    
        public int Id { get; set; }
        [DisplayName("Importance")]
        public string Importance1 { get; set; }
    
        public virtual ICollection<Diary> Diaries { get; set; }
    }
}
