//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDiary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Diaries = new HashSet<Diary>();
        }

        public int Id { get; set; }
        [Required,MinLength(4,ErrorMessage="Username id too short")]
        public string Username { get; set; }
        [Required,MinLength(4,ErrorMessage="Password is too short")]
        public string Password { get; set; }
    
        public virtual ICollection<Diary> Diaries { get; set; }
    }
}
